package com.example.lyceum_application_android_client.models

val users: List<User> = listOf(
    User(
        "sergey_chipura",
        "sergey_chipura@email.com",
        "qwe",
        "Сергей",
        1,
        "Чипура",
        "Петрович"
    ),
    User(
        "nikita_maruschak",
        "nikita_maruschak@email.com",
        "qwe",
        "Никита",
        1,
        "Марусчак",
        "Сергеевич"
    ),
    User(
        "alex_rushakov",
        "alex_rushakov@email.com",
        "qwe",
        "Саша",
        1,
        "Рушаков",
        "Андреевич"
    ),
    User(
        "nikita_serov",
        "nikita_serov@email.com",
        "qwe",
        "Никита",
        1,
        "Серов",
        "Романович"
    ),
    User(
        "serhey_ermuratov",
        "serhey_ermuratov@email.com",
        "qwe",
        "Сергей",
        1,
        "Ермуратов",
        "Сергеевич"
    ),
    User(
        "alex_baharev",
        "alex_baharev@email.com",
        "qwe",
        "Алексей",
        1,
        "Бахарев",
        "Андреевич"
    ),
    User(
        "igor_lemeshev",
        "igor_lemeshev@email.com",
        "qwe",
        "Игорь",
        1,
        "Лемешев",
        "Андреевич"
    ),
    User(
        "alevtina_noschenko",
        "alevtina_noschenko@email.com",
        "qwe",
        "Алевтина",
        1,
        "Нощенко",
        "Сергеевна"
    ),
    User(
        "olga_urevna",
        "olga_urevna@email.com",
        "qwe",
        "Ольга",
        1,
        "Метелева",
        "Юрьевна"
    ),
    User(
        "anastasia_lyagova",
        "anastasia_lyagova@email.com",
        "qwe",
        "Анастасия",
        1,
        "Лягова",
        "Иванова"
    ),
    User(
        "ulia_alashevskya",
        "ulia_alashevskya@email.com",
        "qwe",
        "Юлия",
        1,
        "Алашевская",
        "Максимовна"
    )
)
